config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  resources :users do
    member do
    get :following, :followers
    end
  end
  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="bg-light text-center text-lg-start">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
          Home <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "Help", help_path, class: "nav-link" %>
      </li>
      <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>

      <div class="form-inline my-2 my-lg-0">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
               role="button" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">
              Account <b class="caret"></b>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", current_user, class: "dropdown-item" %>
              <%= link_to "Profile", current_user, class: "dropdown-item"  %>
              <%= link_to "Settings", '#', class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <% end %>
      </div>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all',
       'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
       'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render"layouts/header"%>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <div class="container content-wrapper">
      <%= yield %>
    </div>
    <%= render"layouts/footer"%>
  </body>
</html>